export const detectionStyles = {
  view: 'flex flex-col gap-6',
  header: 'flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-border/40',
  headerLeft: 'flex flex-col gap-1',
  headerActions: 'flex flex-wrap items-center gap-2',
  title: 'text-2xl font-black tracking-tight text-text',
  subtitle: 'text-sm text-text-secondary',
  btn: 'inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-sm',
  btnSm: 'inline-flex items-center justify-center px-2.5 py-1 text-xs font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer',
  btnPrimary: 'inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-primary text-white hover:bg-primary/90 transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-sm',
  btnDanger: 'inline-flex items-center justify-center px-2.5 py-1 text-xs font-semibold rounded-lg bg-danger text-white hover:bg-danger/90 transition-all disabled:opacity-50 cursor-pointer',

  tabs: 'flex flex-wrap gap-1 p-1 rounded-xl bg-surface-low border border-border-subtle w-fit',
  tab: 'px-3 py-1.5 text-sm font-semibold rounded-lg text-text-secondary hover:text-text hover:bg-surface-hover transition-colors',
  tabActive: 'px-3 py-1.5 text-sm font-semibold rounded-lg bg-surface text-text shadow-sm border border-border-subtle',

  statGrid: 'grid grid-cols-2 md:grid-cols-4 gap-4',
  stat: 'bg-surface rounded-2xl border border-border-subtle shadow-sm p-4 flex flex-col gap-1',
  statLabel: 'text-xs font-bold uppercase tracking-wider text-text-tertiary',
  statValue: 'text-2xl font-black text-text',
  statHint: 'text-xs text-text-secondary',

  grid2: 'grid grid-cols-1 lg:grid-cols-2 gap-6',
  card: 'bg-surface rounded-2xl border border-border-subtle shadow-sm p-5 flex flex-col gap-4',
  cardTitle: 'text-base font-bold text-text',
  cardHint: 'text-xs text-text-secondary',

  filterCard: 'bg-surface rounded-2xl border border-border-subtle shadow-sm p-4',
  formRow: 'flex flex-wrap gap-4 items-end',
  field: 'flex flex-col gap-1.5 text-xs font-bold uppercase tracking-wider text-text-secondary',
  input: 'text-sm px-3 py-1.5 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary min-w-[180px] normal-case tracking-normal font-normal',
  select: 'text-sm px-2.5 py-1.5 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary normal-case tracking-normal font-normal',
  textarea: 'w-full text-xs font-mono px-3 py-2 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary min-h-[220px]',
  textareaSm: 'w-full text-sm px-3 py-2 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary min-h-[80px] normal-case tracking-normal font-normal',

  tableCard: 'bg-surface rounded-2xl border border-border-subtle shadow-sm overflow-hidden',
  tableWrapper: 'overflow-x-auto',
  table: 'w-full text-left border-collapse text-sm',
  th: 'px-4 py-3 text-xs font-bold uppercase tracking-wider text-text-tertiary bg-surface-low border-b border-border',
  thNum: 'px-4 py-3 text-xs font-bold uppercase tracking-wider text-text-tertiary bg-surface-low border-b border-border text-right',
  td: 'px-4 py-3 border-b border-border-subtle text-text align-top',
  tdNum: 'px-4 py-3 border-b border-border-subtle text-text text-right tabular-nums',
  tdMuted: 'px-4 py-3 border-b border-border-subtle text-text-secondary text-xs align-top',
  tr: 'hover:bg-surface-hover transition-colors',
  trSelected: 'bg-primary-soft',
  mono: 'font-mono text-xs break-all',
  skeleton: 'font-mono text-xs leading-relaxed break-words p-3 rounded-lg bg-surface-low border border-border-subtle',
  link: 'font-medium text-primary hover:underline cursor-pointer',

  badgeDraft: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-surface-high text-text-secondary capitalize',
  badgeReview: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-warning-soft text-warning capitalize',
  badgePublished: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-success-soft text-success capitalize',
  badgeActive: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-danger-soft text-danger',
  badgeInactive: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-surface-high text-text-secondary',
  badgeNeutral: 'inline-flex items-center px-2 py-0.5 rounded-full text-[11px] font-bold bg-surface-high text-text-secondary',

  mappingRow: 'flex flex-wrap items-center gap-2',
  placeholder: 'px-1.5 py-0.5 rounded bg-surface-high font-mono text-xs text-text border border-border-subtle',
  errorBanner: 'p-3 rounded-lg bg-danger-soft border border-danger/20 text-danger text-sm font-medium',
  successBanner: 'p-3 rounded-lg bg-success-soft border border-success/20 text-success text-sm font-medium',
  list: 'flex flex-col gap-2 text-sm',
  historyItem: 'flex flex-col gap-1 p-3 rounded-lg bg-surface-low border border-border-subtle text-xs',
  dl: 'grid grid-cols-[160px_1fr] gap-y-2 text-sm',
  dt: 'font-semibold text-text-secondary',
  dd: 'text-text',
} as const;
