export const dashboardStyles = {
  view: 'flex flex-col gap-6',
  header: 'flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-border/40',
  headerLeft: 'flex flex-col gap-1',
  statusPill: 'inline-flex items-center gap-2 px-2.5 py-1 rounded-full text-xs font-semibold bg-secondary-soft text-secondary border border-secondary/20 w-fit',
  liveDot: 'h-2 w-2 rounded-full bg-secondary animate-pulse',
  title: 'text-2xl font-black tracking-tight text-text',
  subtitle: 'text-sm text-text-secondary',
  refreshBtn: 'inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-sm',
  sections: 'flex flex-col gap-8 transition-opacity duration-200',
  refreshing: 'opacity-70 pointer-events-none',
  sectionBlock: 'flex flex-col gap-4',
  sectionTitle: 'text-sm font-bold uppercase tracking-wider text-text-tertiary',
  bentoGrid: 'grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3.5',
  bentoStat: 'flex flex-col justify-between min-h-[128px] p-[18px_20px] rounded-card bg-surface border border-border-subtle shadow-sm hover:-translate-y-0.5 hover:shadow-md hover:border-primary/40 transition-all duration-150',
  bentoHighlight: 'bg-gradient-to-br from-surface to-surface-low border-primary/25',
  bentoTop: 'flex items-center justify-between mb-4',
  bentoIconPod: 'w-[34px] h-[34px] rounded-[10px] flex items-center justify-center text-[15px] font-extrabold',
  podOcean: 'bg-ocean/15 text-ocean',
  podEmerald: 'bg-secondary/15 text-secondary',
  podViolet: 'bg-violet/15 text-violet',
  podPrimary: 'bg-primary/15 text-primary',
  bentoBadge: 'text-[11px] font-bold rounded-full px-2 py-0.5',
  badgeSecondary: 'bg-secondary-soft text-secondary',
  badgeNeutral: 'bg-surface-high text-text-secondary',
  statContent: 'flex flex-col',
  bentoLabel: 'text-[13px] font-semibold text-text-secondary mb-1 block',
  bentoAmount: 'text-[22px] font-extrabold text-text tabular-nums tracking-tight block',
} as const;
