export const loginStyles = {
  page: 'flex min-h-screen flex-col items-center justify-center bg-bg p-6',
  hero: 'text-center mb-6',
  logoWrapper: 'flex justify-center mb-3',
  title: 'text-2xl font-extrabold tracking-tight text-text',
  titleAccent: 'text-primary',
  divider: 'h-1 w-12 mx-auto my-3 bg-gradient-to-r from-primary via-violet to-secondary rounded-full',
  subtitle: 'text-sm text-text-secondary',
  panel: 'w-full max-w-md rounded-2xl bg-surface p-8 border border-border shadow-lg',
  panelTitle: 'text-xl font-bold text-text mb-6',
  form: 'flex flex-col gap-4',
  errorBanner: 'p-3 rounded-lg bg-danger-soft border border-danger/20 text-danger text-sm font-medium',
  fieldGroup: 'flex flex-col gap-1.5',
  label: 'text-xs font-semibold text-text-secondary uppercase tracking-wider',
  input: 'w-full px-4 py-2.5 rounded-lg border border-border bg-input-bg text-text text-sm focus:outline-none focus:ring-2 focus:ring-primary focus:border-transparent transition-all',
  inputInvalid: 'w-full px-4 py-2.5 rounded-lg border border-danger bg-danger-soft text-text text-sm focus:outline-none focus:ring-2 focus:ring-danger transition-all',
  fieldError: 'text-xs text-danger font-medium mt-1',
  submitButton: 'w-full mt-2 py-3 px-4 rounded-lg bg-primary hover:bg-primary-hover text-on-primary font-semibold text-sm shadow-md hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer',
} as const;
