export const usersStyles = {
  view: 'flex flex-col gap-6',
  header: 'flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-border/40',
  headerLeft: 'flex flex-col gap-1',
  title: 'text-2xl font-black tracking-tight text-text',
  subtitle: 'text-sm text-text-secondary flex items-center gap-2 flex-wrap',
  backLink: 'text-sm font-semibold text-primary hover:underline inline-flex items-center gap-1 mb-1',
  refreshBtn: 'inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-sm',
  filterCard: 'bg-surface rounded-2xl border border-border-subtle shadow-sm p-4',
  formRow: 'flex flex-wrap gap-4 items-center',
  filterLabel: 'flex flex-col sm:flex-row sm:items-center gap-2 text-xs font-bold uppercase tracking-wider text-text-secondary',
  inputSm: 'text-xs px-3 py-1.5 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary min-w-[200px]',
  selectSm: 'text-xs px-2.5 py-1.5 rounded-lg border border-border bg-input-bg text-text focus:outline-none focus:ring-1 focus:ring-primary',
  card: 'bg-surface rounded-2xl border border-border-subtle shadow-sm overflow-hidden p-6',
  tableCard: 'bg-surface rounded-2xl border border-border-subtle shadow-sm overflow-hidden',
  tableWrapper: 'overflow-x-auto',
  table: 'w-full text-left border-collapse text-sm',
  th: 'px-4 py-3 text-xs font-bold uppercase tracking-wider text-text-tertiary bg-surface-low border-b border-border',
  td: 'px-4 py-3.5 border-b border-border-subtle text-text',
  tdMuted: 'px-4 py-3.5 border-b border-border-subtle text-text-secondary text-[13px]',
  tdDate: 'px-4 py-3.5 border-b border-border-subtle text-text-tertiary text-[13px]',
  tr: 'hover:bg-surface-hover transition-colors',
  link: 'font-medium text-primary hover:underline',
  badgeActive: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-success-soft text-success',
  badgeSuspended: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-danger-soft text-danger',
  badgeRole: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-primary-soft text-primary capitalize',
  badgeRoleAdmin: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-violet/15 text-violet uppercase tracking-wide',
  badgeRolePro: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-amber-500/15 text-amber-500 uppercase tracking-wide',
  badgeRoleLifetime: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-emerald-500/15 text-emerald-500 uppercase tracking-wide',
  detailGrid: 'grid grid-cols-1 md:grid-cols-2 gap-6',
  sectionTitle: 'text-base font-bold text-text mb-4 pb-2 border-b border-border-subtle',
  dl: 'grid grid-cols-1 gap-y-3 sm:grid-cols-[140px_1fr] sm:gap-y-3.5 text-sm',
  dt: 'font-semibold text-text-secondary',
  dd: 'text-text break-words',
  formGroup: 'flex flex-col gap-3 mb-6 last:mb-0',
  formLabel: 'text-xs font-bold uppercase tracking-wider text-text-secondary',
  select: 'w-full px-3 py-2 rounded-lg border border-border bg-input-bg text-text text-sm focus:outline-none focus:ring-2 focus:ring-primary',
  btnSecondary: 'inline-flex items-center justify-center px-4 py-2 text-sm font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 cursor-pointer shadow-sm',
  btnDanger: 'inline-flex items-center justify-center px-4 py-2 text-sm font-semibold rounded-lg bg-danger hover:bg-danger/90 text-white transition-all disabled:opacity-50 cursor-pointer shadow-sm',
  errorBanner: 'p-3 rounded-lg bg-danger-soft border border-danger/20 text-danger text-sm font-medium mb-4',
} as const;
