export const aiStyles = {
  view: 'flex flex-col gap-6',
  header: 'flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-2 border-b border-border/40',
  headerLeft: 'flex flex-col gap-1',
  statusPill: 'inline-flex items-center gap-2 px-2.5 py-1 rounded-full text-xs font-semibold bg-secondary-soft text-secondary border border-secondary/20 w-fit',
  liveDot: 'h-2 w-2 rounded-full bg-secondary animate-pulse',
  title: 'text-2xl font-black tracking-tight text-text',
  subtitle: 'text-sm text-text-secondary',
  refreshBtn: 'inline-flex items-center justify-center gap-2 px-4 py-2 text-sm font-semibold rounded-lg bg-surface border border-border hover:bg-surface-hover text-text transition-all disabled:opacity-50 disabled:cursor-not-allowed cursor-pointer shadow-sm',
  tableCard: 'bg-surface rounded-2xl border border-border-subtle shadow-sm overflow-hidden',
  tableWrapper: 'overflow-x-auto',
  table: 'w-full text-left border-collapse text-sm',
  th: 'px-4 py-3 text-xs font-bold uppercase tracking-wider text-text-tertiary bg-surface-low border-b border-border',
  td: 'px-4 py-3.5 border-b border-border-subtle text-text',
  tdDate: 'px-4 py-3.5 border-b border-border-subtle text-text-tertiary text-[13px]',
  tr: 'hover:bg-surface-hover transition-colors',
  link: 'font-medium text-primary hover:underline',
  userMeta: 'text-[11px] text-text-tertiary mt-0.5',
  messageCell: 'max-w-[300px] px-4 py-3.5 border-b border-border-subtle',
  messageText: 'block font-medium text-text truncate',
  badgeSecondary: 'inline-flex items-center px-2 py-0.5 rounded-full text-xs font-bold bg-secondary-soft text-secondary',
} as const;
